// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Esp32TableSaw_SL

#include "../ui.h"

void ui_ScrMove_screen_init(void)
{
ui_ScrMove = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScrMove, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel2 = lv_obj_create(ui_ScrMove);
lv_obj_set_height( ui_Panel2, 40);
lv_obj_set_width( ui_Panel2, lv_pct(100));
lv_obj_set_align( ui_Panel2, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x2A2929), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblPosition = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_lblPosition, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblPosition, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblPosition, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblPosition,"0");
lv_obj_set_style_text_color(ui_lblPosition, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblPosition, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel5 = lv_obj_create(ui_ScrMove);
lv_obj_set_height( ui_Panel5, 280);
lv_obj_set_width( ui_Panel5, lv_pct(100));
lv_obj_set_align( ui_Panel5, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_Panel5,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x2A2929), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKey1 = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKey1, lv_pct(22));
lv_obj_set_height( ui_ButtonKey1, lv_pct(16));
lv_obj_set_align( ui_ButtonKey1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonKey1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKey1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKey1, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKey1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKey1 = lv_label_create(ui_ButtonKey1);
lv_obj_set_width( ui_LabelKey1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKey1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKey1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKey1,"1");
lv_obj_set_style_text_color(ui_LabelKey1, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKey1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKey1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKey2 = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKey2, lv_pct(22));
lv_obj_set_height( ui_ButtonKey2, lv_pct(16));
lv_obj_set_align( ui_ButtonKey2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonKey2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKey2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKey2, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKey2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKey2 = lv_label_create(ui_ButtonKey2);
lv_obj_set_width( ui_LabelKey2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKey2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKey2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKey2,"2");
lv_obj_set_style_text_color(ui_LabelKey2, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKey2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKey2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKey3 = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKey3, lv_pct(22));
lv_obj_set_height( ui_ButtonKey3, lv_pct(16));
lv_obj_set_align( ui_ButtonKey3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonKey3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKey3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKey3, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKey3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKey3 = lv_label_create(ui_ButtonKey3);
lv_obj_set_width( ui_LabelKey3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKey3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKey3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKey3,"3");
lv_obj_set_style_text_color(ui_LabelKey3, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKey3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKey3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKeyDel = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKeyDel, lv_pct(22));
lv_obj_set_height( ui_ButtonKeyDel, lv_pct(16));
lv_obj_set_align( ui_ButtonKeyDel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonKeyDel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKeyDel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKeyDel, lv_color_hex(0xCA0C18), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKeyDel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKeyDel = lv_label_create(ui_ButtonKeyDel);
lv_obj_set_width( ui_LabelKeyDel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKeyDel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKeyDel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKeyDel,"DEL");
lv_obj_set_style_text_color(ui_LabelKeyDel, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKeyDel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKeyDel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelKeyDel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKey4 = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKey4, lv_pct(22));
lv_obj_set_height( ui_ButtonKey4, lv_pct(16));
lv_obj_set_align( ui_ButtonKey4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonKey4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKey4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKey4, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKey4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKey4 = lv_label_create(ui_ButtonKey4);
lv_obj_set_width( ui_LabelKey4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKey4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKey4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKey4,"4");
lv_obj_set_style_text_color(ui_LabelKey4, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKey4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKey4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKey5 = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKey5, lv_pct(22));
lv_obj_set_height( ui_ButtonKey5, lv_pct(16));
lv_obj_set_align( ui_ButtonKey5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonKey5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKey5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKey5, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKey5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKey5 = lv_label_create(ui_ButtonKey5);
lv_obj_set_width( ui_LabelKey5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKey5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKey5, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKey5,"5");
lv_obj_set_style_text_color(ui_LabelKey5, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKey5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKey5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKey6 = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKey6, lv_pct(22));
lv_obj_set_height( ui_ButtonKey6, lv_pct(16));
lv_obj_set_align( ui_ButtonKey6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonKey6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKey6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKey6, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKey6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKey6 = lv_label_create(ui_ButtonKey6);
lv_obj_set_width( ui_LabelKey6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKey6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKey6, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKey6,"6");
lv_obj_set_style_text_color(ui_LabelKey6, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKey6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKey6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKeyPos1 = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKeyPos1, lv_pct(22));
lv_obj_set_height( ui_ButtonKeyPos1, lv_pct(16));
lv_obj_set_align( ui_ButtonKeyPos1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonKeyPos1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKeyPos1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKeyPos1, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKeyPos1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKeyPos1 = lv_label_create(ui_ButtonKeyPos1);
lv_obj_set_width( ui_LabelKeyPos1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKeyPos1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKeyPos1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKeyPos1,"Pos 1");
lv_obj_set_style_text_color(ui_LabelKeyPos1, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKeyPos1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKeyPos1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKey7 = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKey7, lv_pct(22));
lv_obj_set_height( ui_ButtonKey7, lv_pct(16));
lv_obj_set_align( ui_ButtonKey7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonKey7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKey7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKey7, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKey7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKey7 = lv_label_create(ui_ButtonKey7);
lv_obj_set_width( ui_LabelKey7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKey7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKey7, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKey7,"7");
lv_obj_set_style_text_color(ui_LabelKey7, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKey7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKey7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKey8 = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKey8, lv_pct(22));
lv_obj_set_height( ui_ButtonKey8, lv_pct(16));
lv_obj_set_x( ui_ButtonKey8, 0 );
lv_obj_set_y( ui_ButtonKey8, -1 );
lv_obj_set_align( ui_ButtonKey8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonKey8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKey8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKey8, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKey8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKey8 = lv_label_create(ui_ButtonKey8);
lv_obj_set_width( ui_LabelKey8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKey8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKey8, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKey8,"8");
lv_obj_set_style_text_color(ui_LabelKey8, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKey8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKey8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKey9 = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKey9, lv_pct(22));
lv_obj_set_height( ui_ButtonKey9, lv_pct(16));
lv_obj_set_x( ui_ButtonKey9, 1 );
lv_obj_set_y( ui_ButtonKey9, 0 );
lv_obj_set_align( ui_ButtonKey9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonKey9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKey9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKey9, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKey9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKey9 = lv_label_create(ui_ButtonKey9);
lv_obj_set_width( ui_LabelKey9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKey9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKey9, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKey9,"9");
lv_obj_set_style_text_color(ui_LabelKey9, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKey9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKey9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKeyPos2 = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKeyPos2, lv_pct(22));
lv_obj_set_height( ui_ButtonKeyPos2, lv_pct(16));
lv_obj_set_align( ui_ButtonKeyPos2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonKeyPos2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKeyPos2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKeyPos2, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKeyPos2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKeyPos2 = lv_label_create(ui_ButtonKeyPos2);
lv_obj_set_width( ui_LabelKeyPos2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKeyPos2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKeyPos2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKeyPos2,"Pos 2");
lv_obj_set_style_text_color(ui_LabelKeyPos2, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKeyPos2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKeyPos2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKeyComma = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKeyComma, lv_pct(22));
lv_obj_set_height( ui_ButtonKeyComma, lv_pct(16));
lv_obj_set_align( ui_ButtonKeyComma, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonKeyComma, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKeyComma, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKeyComma, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKeyComma, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKeyComma = lv_label_create(ui_ButtonKeyComma);
lv_obj_set_width( ui_LabelKeyComma, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKeyComma, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKeyComma, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKeyComma,",");
lv_obj_set_style_text_color(ui_LabelKeyComma, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKeyComma, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKeyComma, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKey0 = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKey0, lv_pct(22));
lv_obj_set_height( ui_ButtonKey0, lv_pct(16));
lv_obj_set_align( ui_ButtonKey0, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonKey0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKey0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKey0, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKey0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKey0 = lv_label_create(ui_ButtonKey0);
lv_obj_set_width( ui_LabelKey0, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKey0, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKey0, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKey0,"0");
lv_obj_set_style_text_color(ui_LabelKey0, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKey0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKey0, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKey05 = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKey05, lv_pct(22));
lv_obj_set_height( ui_ButtonKey05, lv_pct(16));
lv_obj_set_align( ui_ButtonKey05, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonKey05, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKey05, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKey05, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKey05, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKey05 = lv_label_create(ui_ButtonKey05);
lv_obj_set_width( ui_LabelKey05, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKey05, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKey05, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKey05,".5");
lv_obj_set_style_text_color(ui_LabelKey05, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKey05, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKey05, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKeyPos3 = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKeyPos3, lv_pct(22));
lv_obj_set_height( ui_ButtonKeyPos3, lv_pct(16));
lv_obj_set_align( ui_ButtonKeyPos3, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_ButtonKeyPos3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKeyPos3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKeyPos3, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKeyPos3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKeyPos3 = lv_label_create(ui_ButtonKeyPos3);
lv_obj_set_width( ui_LabelKeyPos3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKeyPos3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKeyPos3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKeyPos3,"Pos 3");
lv_obj_set_style_text_color(ui_LabelKeyPos3, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKeyPos3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKeyPos3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKeyValidate = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKeyValidate, lv_pct(73));
lv_obj_set_height( ui_ButtonKeyValidate, lv_pct(22));
lv_obj_set_align( ui_ButtonKeyValidate, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_ButtonKeyValidate, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKeyValidate, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKeyValidate, lv_color_hex(0x26CB0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKeyValidate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKeyValidate = lv_label_create(ui_ButtonKeyValidate);
lv_obj_set_width( ui_LabelKeyValidate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKeyValidate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKeyValidate, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelKeyValidate,"GO");
lv_obj_set_style_text_color(ui_LabelKeyValidate, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelKeyValidate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelKeyValidate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonKeySettings = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_ButtonKeySettings, lv_pct(22));
lv_obj_set_height( ui_ButtonKeySettings, lv_pct(22));
lv_obj_set_align( ui_ButtonKeySettings, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_ButtonKeySettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonKeySettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonKeySettings, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonKeySettings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelKeySettings = lv_img_create(ui_ButtonKeySettings);
lv_img_set_src(ui_LabelKeySettings, &ui_img_478973782);
lv_obj_set_width( ui_LabelKeySettings, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelKeySettings, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelKeySettings, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LabelKeySettings, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LabelKeySettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_ButtonKey1, ui_event_ButtonKey1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKey2, ui_event_ButtonKey2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKey3, ui_event_ButtonKey3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKeyDel, ui_event_ButtonKeyDel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKey4, ui_event_ButtonKey4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKey5, ui_event_ButtonKey5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKey6, ui_event_ButtonKey6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKeyPos1, ui_event_ButtonKeyPos1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKey7, ui_event_ButtonKey7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKey8, ui_event_ButtonKey8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKey9, ui_event_ButtonKey9, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKeyPos2, ui_event_ButtonKeyPos2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKeyComma, ui_event_ButtonKeyComma, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKey0, ui_event_ButtonKey0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKey05, ui_event_ButtonKey05, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKeyPos3, ui_event_ButtonKeyPos3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKeyValidate, ui_event_ButtonKeyValidate, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonKeySettings, ui_event_ButtonKeySettings, LV_EVENT_ALL, NULL);

}
