// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Esp32TableSaw_SL

#include "../ui.h"

void ui_ScrSetStep_screen_init(void)
{
    ui_ScrSetStep = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrSetStep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_ScrSetStep);
    lv_obj_set_height(ui_Panel3, 40);
    lv_obj_set_width(ui_Panel3, lv_pct(100));
    lv_obj_set_align(ui_Panel3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x2A2929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPosition1 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_lblPosition1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPosition1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblPosition1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPosition1, "0");
    lv_obj_set_style_text_color(ui_lblPosition1, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblPosition1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_ScrSetStep);
    lv_obj_set_height(ui_Panel4, 280);
    lv_obj_set_width(ui_Panel4, lv_pct(100));
    lv_obj_set_align(ui_Panel4, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x2A2929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn10 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Btn10, lv_pct(22));
    lv_obj_set_height(ui_Btn10, lv_pct(16));
    lv_obj_set_align(ui_Btn10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Btn10, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Btn10);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "1");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn11 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Btn11, lv_pct(22));
    lv_obj_set_height(ui_Btn11, lv_pct(16));
    lv_obj_set_align(ui_Btn11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Btn11, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Btn11);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "2");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label25, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn12 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Btn12, lv_pct(22));
    lv_obj_set_height(ui_Btn12, lv_pct(16));
    lv_obj_set_align(ui_Btn12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Btn12, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Btn12);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "3");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label26, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnDel1 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_BtnDel1, lv_pct(22));
    lv_obj_set_height(ui_BtnDel1, lv_pct(16));
    lv_obj_set_align(ui_BtnDel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnDel1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnDel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnDel1, lv_color_hex(0xCA0C18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnDel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_BtnDel1);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "DEL");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label27, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn13 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Btn13, lv_pct(22));
    lv_obj_set_height(ui_Btn13, lv_pct(16));
    lv_obj_set_align(ui_Btn13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Btn13, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Btn13);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "4");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label28, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn14 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Btn14, lv_pct(22));
    lv_obj_set_height(ui_Btn14, lv_pct(16));
    lv_obj_set_align(ui_Btn14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Btn14, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Btn14);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "5");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label29, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn15 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Btn15, lv_pct(22));
    lv_obj_set_height(ui_Btn15, lv_pct(16));
    lv_obj_set_align(ui_Btn15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Btn15, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Btn15);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "6");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label30, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn16 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Btn16, lv_pct(22));
    lv_obj_set_height(ui_Btn16, lv_pct(16));
    lv_obj_set_align(ui_Btn16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Btn16, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Btn16);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label31, ".5");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label31, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn17 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Btn17, lv_pct(22));
    lv_obj_set_height(ui_Btn17, lv_pct(16));
    lv_obj_set_align(ui_Btn17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Btn17, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Btn17);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "7");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label32, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn18 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Btn18, lv_pct(22));
    lv_obj_set_height(ui_Btn18, lv_pct(16));
    lv_obj_set_align(ui_Btn18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Btn18, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Btn18);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "8");
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label33, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn19 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Btn19, lv_pct(22));
    lv_obj_set_height(ui_Btn19, lv_pct(16));
    lv_obj_set_align(ui_Btn19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Btn19, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_Btn19);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "9");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label34, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn20 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Btn20, lv_pct(22));
    lv_obj_set_height(ui_Btn20, lv_pct(16));
    lv_obj_set_align(ui_Btn20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Btn20, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_Btn20);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label35, ".25");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label35, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnComma1 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_BtnComma1, lv_pct(22));
    lv_obj_set_height(ui_BtnComma1, lv_pct(16));
    lv_obj_set_align(ui_BtnComma1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnComma1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnComma1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnComma1, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnComma1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_BtnComma1);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, ",");
    lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label36, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn21 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Btn21, lv_pct(22));
    lv_obj_set_height(ui_Btn21, lv_pct(16));
    lv_obj_set_align(ui_Btn21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Btn21, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_Btn21);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "0");
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label37, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn22 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Btn22, lv_pct(22));
    lv_obj_set_height(ui_Btn22, lv_pct(16));
    lv_obj_set_align(ui_Btn22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Btn22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Btn22, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_Btn22);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, ".33");
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label38, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btn23 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Btn23, lv_pct(22));
    lv_obj_set_height(ui_Btn23, lv_pct(16));
    lv_obj_set_align(ui_Btn23, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Btn23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Btn23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Btn23, lv_color_hex(0x3A393B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Btn23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Btn23);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, ".125");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label39, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnGo1 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_BtnGo1, lv_pct(73));
    lv_obj_set_height(ui_BtnGo1, lv_pct(22));
    lv_obj_set_align(ui_BtnGo1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_BtnGo1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnGo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnGo1, lv_color_hex(0x26CB0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnGo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_BtnGo1);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "Set Step");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label40, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnClose2 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_BtnClose2, lv_pct(22));
    lv_obj_set_height(ui_BtnClose2, lv_pct(22));
    lv_obj_set_align(ui_BtnClose2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_BtnClose2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnClose2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnClose2, lv_color_hex(0xCA0C18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnClose2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_BtnClose2);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label41, "Close");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label41, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_BtnClose2);
    lv_img_set_src(ui_Image8, &ui_img_1297254713);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image8, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Label3, ui_event_Label3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn10, ui_event_Btn10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn11, ui_event_Btn11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn12, ui_event_Btn12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnDel1, ui_event_BtnDel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn13, ui_event_Btn13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn14, ui_event_Btn14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn15, ui_event_Btn15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn16, ui_event_Btn16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn17, ui_event_Btn17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn18, ui_event_Btn18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn19, ui_event_Btn19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn20, ui_event_Btn20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnComma1, ui_event_BtnComma1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn21, ui_event_Btn21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn22, ui_event_Btn22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btn23, ui_event_Btn23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnGo1, ui_event_BtnGo1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnClose2, ui_event_BtnClose2, LV_EVENT_ALL, NULL);

}
