// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Esp32TableSaw_SL

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScrMove
void ui_ScrMove_screen_init(void);
lv_obj_t *ui_ScrMove;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_lblPosition;
lv_obj_t *ui_Panel5;
void ui_event_ButtonKey1( lv_event_t * e);
lv_obj_t *ui_ButtonKey1;
lv_obj_t *ui_LabelKey1;
void ui_event_ButtonKey2( lv_event_t * e);
lv_obj_t *ui_ButtonKey2;
lv_obj_t *ui_LabelKey2;
void ui_event_ButtonKey3( lv_event_t * e);
lv_obj_t *ui_ButtonKey3;
lv_obj_t *ui_LabelKey3;
void ui_event_ButtonKeyDel( lv_event_t * e);
lv_obj_t *ui_ButtonKeyDel;
lv_obj_t *ui_LabelKeyDel;
void ui_event_ButtonKey4( lv_event_t * e);
lv_obj_t *ui_ButtonKey4;
lv_obj_t *ui_LabelKey4;
void ui_event_ButtonKey5( lv_event_t * e);
lv_obj_t *ui_ButtonKey5;
lv_obj_t *ui_LabelKey5;
void ui_event_ButtonKey6( lv_event_t * e);
lv_obj_t *ui_ButtonKey6;
lv_obj_t *ui_LabelKey6;
void ui_event_ButtonKeyPos1( lv_event_t * e);
lv_obj_t *ui_ButtonKeyPos1;
lv_obj_t *ui_LabelKeyPos1;
void ui_event_ButtonKey7( lv_event_t * e);
lv_obj_t *ui_ButtonKey7;
lv_obj_t *ui_LabelKey7;
void ui_event_ButtonKey8( lv_event_t * e);
lv_obj_t *ui_ButtonKey8;
lv_obj_t *ui_LabelKey8;
void ui_event_ButtonKey9( lv_event_t * e);
lv_obj_t *ui_ButtonKey9;
lv_obj_t *ui_LabelKey9;
void ui_event_ButtonKeyPos2( lv_event_t * e);
lv_obj_t *ui_ButtonKeyPos2;
lv_obj_t *ui_LabelKeyPos2;
void ui_event_ButtonKeyComma( lv_event_t * e);
lv_obj_t *ui_ButtonKeyComma;
lv_obj_t *ui_LabelKeyComma;
void ui_event_ButtonKey0( lv_event_t * e);
lv_obj_t *ui_ButtonKey0;
lv_obj_t *ui_LabelKey0;
void ui_event_ButtonKey05( lv_event_t * e);
lv_obj_t *ui_ButtonKey05;
lv_obj_t *ui_LabelKey05;
void ui_event_ButtonKeyPos3( lv_event_t * e);
lv_obj_t *ui_ButtonKeyPos3;
lv_obj_t *ui_LabelKeyPos3;
void ui_event_ButtonKeyValidate( lv_event_t * e);
lv_obj_t *ui_ButtonKeyValidate;
lv_obj_t *ui_LabelKeyValidate;
void ui_event_ButtonKeySettings( lv_event_t * e);
lv_obj_t *ui_ButtonKeySettings;
lv_obj_t *ui_LabelKeySettings;


// SCREEN: ui_ScrSettings
void ui_ScrSettings_screen_init(void);
lv_obj_t *ui_ScrSettings;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_ButtonSettingsPos1Enter;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Image3;
lv_obj_t *ui_BtnPos2;
lv_obj_t *ui_Label20;
lv_obj_t *ui_Image4;
lv_obj_t *ui_BtnPos3;
lv_obj_t *ui_Label21;
lv_obj_t *ui_Image5;
lv_obj_t *ui_BtnProbe;
lv_obj_t *ui_Label22;
lv_obj_t *ui_Image6;
void ui_event_BtnSteps( lv_event_t * e);
lv_obj_t *ui_BtnSteps;
lv_obj_t *ui_Label23;
lv_obj_t *ui_Image7;
void ui_event_BtnClose( lv_event_t * e);
lv_obj_t *ui_BtnClose;
lv_obj_t *ui_Label24;
lv_obj_t *ui_Image1;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_settings_[1] = {&ui_img_settings_24_png};
const lv_img_dsc_t *ui_imgset_settings_fill0_wght400_grad0_opsz[2] = {&ui_img_settings_fill0_wght400_grad0_opsz24_png, &ui_img_settings_fill0_wght400_grad0_opsz48_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonKey1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKey1Clicked( e );
}
}
void ui_event_ButtonKey2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKey2Clicked( e );
}
}
void ui_event_ButtonKey3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKey3Clicked( e );
}
}
void ui_event_ButtonKeyDel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKeyDelClicked( e );
}
}
void ui_event_ButtonKey4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKey4Clicked( e );
}
}
void ui_event_ButtonKey5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKey5Clicked( e );
}
}
void ui_event_ButtonKey6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKey6Clicked( e );
}
}
void ui_event_ButtonKeyPos1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKeyPos1Clicked( e );
}
}
void ui_event_ButtonKey7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKey7Clicked( e );
}
}
void ui_event_ButtonKey8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKey8Clicked( e );
}
}
void ui_event_ButtonKey9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKey9Clicked( e );
}
}
void ui_event_ButtonKeyPos2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKeyPos2Clicked( e );
}
}
void ui_event_ButtonKeyComma( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKeyCommaClicked( e );
}
}
void ui_event_ButtonKey0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKey1Clicked( e );
}
}
void ui_event_ButtonKey05( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKey05Clicked( e );
}
}
void ui_event_ButtonKeyPos3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKeyPos3Clicked( e );
}
}
void ui_event_ButtonKeyValidate( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKeyValidateClicked( e );
}
}
void ui_event_ButtonKeySettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonKeySettingsClicked( e );
}
}
void ui_event_BtnSteps( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScrSetStep, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScrSetStep_screen_init);
}
}
void ui_event_BtnClose( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScrMove, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScrMove_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_ScrMove_screen_init();
ui_ScrSettings_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ScrMove);
}
