// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Esp32TableSaw_SL

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_ScrMove
void ui_ScrMove_screen_init(void);
lv_obj_t * ui_ScrMove;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_lblPosition;
lv_obj_t * ui_Panel5;
void ui_event_Btn1(lv_event_t * e);
lv_obj_t * ui_Btn1;
void ui_event_Label1(lv_event_t * e);
lv_obj_t * ui_Label1;
void ui_event_Btn2(lv_event_t * e);
lv_obj_t * ui_Btn2;
lv_obj_t * ui_Label2;
void ui_event_Btn3(lv_event_t * e);
lv_obj_t * ui_Btn3;
lv_obj_t * ui_Label4;
void ui_event_BtnDel(lv_event_t * e);
lv_obj_t * ui_BtnDel;
lv_obj_t * ui_Label5;
void ui_event_Btn4(lv_event_t * e);
lv_obj_t * ui_Btn4;
lv_obj_t * ui_Label6;
void ui_event_Btn5(lv_event_t * e);
lv_obj_t * ui_Btn5;
lv_obj_t * ui_Label7;
void ui_event_Btn6(lv_event_t * e);
lv_obj_t * ui_Btn6;
lv_obj_t * ui_Label8;
void ui_event_Btn05(lv_event_t * e);
lv_obj_t * ui_Btn05;
lv_obj_t * ui_Label9;
void ui_event_Btn7(lv_event_t * e);
lv_obj_t * ui_Btn7;
lv_obj_t * ui_Label10;
void ui_event_Btn8(lv_event_t * e);
lv_obj_t * ui_Btn8;
lv_obj_t * ui_Label11;
void ui_event_Btn9(lv_event_t * e);
lv_obj_t * ui_Btn9;
lv_obj_t * ui_Label12;
void ui_event_Btn025(lv_event_t * e);
lv_obj_t * ui_Btn025;
lv_obj_t * ui_Label13;
void ui_event_BtnComma(lv_event_t * e);
lv_obj_t * ui_BtnComma;
lv_obj_t * ui_Label14;
void ui_event_Btn0(lv_event_t * e);
lv_obj_t * ui_Btn0;
lv_obj_t * ui_Label15;
void ui_event_Btn033(lv_event_t * e);
lv_obj_t * ui_Btn033;
lv_obj_t * ui_Label16;
void ui_event_Btn0125(lv_event_t * e);
lv_obj_t * ui_Btn0125;
lv_obj_t * ui_Label17;
void ui_event_BtnGo(lv_event_t * e);
lv_obj_t * ui_BtnGo;
lv_obj_t * ui_Label18;
void ui_event_BtnSettings(lv_event_t * e);
lv_obj_t * ui_BtnSettings;
lv_obj_t * ui_Image2;

// SCREEN: ui_ScrSettings
void ui_ScrSettings_screen_init(void);
lv_obj_t * ui_ScrSettings;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_BtnPos1;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Image3;
lv_obj_t * ui_BtnPos2;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Image4;
lv_obj_t * ui_BtnPos3;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Image5;
lv_obj_t * ui_BtnProbe;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Image6;
void ui_event_BtnSteps(lv_event_t * e);
lv_obj_t * ui_BtnSteps;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Image7;
void ui_event_BtnClose(lv_event_t * e);
lv_obj_t * ui_BtnClose;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Image1;

// SCREEN: ui_ScrSetStep
void ui_ScrSetStep_screen_init(void);
lv_obj_t * ui_ScrSetStep;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_lblPosition1;
lv_obj_t * ui_Panel4;
void ui_event_Btn10(lv_event_t * e);
lv_obj_t * ui_Btn10;
void ui_event_Label3(lv_event_t * e);
lv_obj_t * ui_Label3;
void ui_event_Btn11(lv_event_t * e);
lv_obj_t * ui_Btn11;
lv_obj_t * ui_Label25;
void ui_event_Btn12(lv_event_t * e);
lv_obj_t * ui_Btn12;
lv_obj_t * ui_Label26;
void ui_event_BtnDel1(lv_event_t * e);
lv_obj_t * ui_BtnDel1;
lv_obj_t * ui_Label27;
void ui_event_Btn13(lv_event_t * e);
lv_obj_t * ui_Btn13;
lv_obj_t * ui_Label28;
void ui_event_Btn14(lv_event_t * e);
lv_obj_t * ui_Btn14;
lv_obj_t * ui_Label29;
void ui_event_Btn15(lv_event_t * e);
lv_obj_t * ui_Btn15;
lv_obj_t * ui_Label30;
void ui_event_Btn16(lv_event_t * e);
lv_obj_t * ui_Btn16;
lv_obj_t * ui_Label31;
void ui_event_Btn17(lv_event_t * e);
lv_obj_t * ui_Btn17;
lv_obj_t * ui_Label32;
void ui_event_Btn18(lv_event_t * e);
lv_obj_t * ui_Btn18;
lv_obj_t * ui_Label33;
void ui_event_Btn19(lv_event_t * e);
lv_obj_t * ui_Btn19;
lv_obj_t * ui_Label34;
void ui_event_Btn20(lv_event_t * e);
lv_obj_t * ui_Btn20;
lv_obj_t * ui_Label35;
void ui_event_BtnComma1(lv_event_t * e);
lv_obj_t * ui_BtnComma1;
lv_obj_t * ui_Label36;
void ui_event_Btn21(lv_event_t * e);
lv_obj_t * ui_Btn21;
lv_obj_t * ui_Label37;
void ui_event_Btn22(lv_event_t * e);
lv_obj_t * ui_Btn22;
lv_obj_t * ui_Label38;
void ui_event_Btn23(lv_event_t * e);
lv_obj_t * ui_Btn23;
lv_obj_t * ui_Label39;
void ui_event_BtnGo1(lv_event_t * e);
lv_obj_t * ui_BtnGo1;
lv_obj_t * ui_Label40;
void ui_event_BtnClose2(lv_event_t * e);
lv_obj_t * ui_BtnClose2;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Image8;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_settings_fill0_wght400_grad0_opsz[2] = {&ui_img_settings_fill0_wght400_grad0_opsz48_png, &ui_img_settings_fill0_wght400_grad0_opsz24_png};
const lv_img_dsc_t * ui_imgset_settings_[1] = {&ui_img_settings_24_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Btn1(lv_event_t * e)
{
    LV_LOG_USER("Clicked (src)");
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("Clicked (LV_EVENT_CLICKED)");
        Move1Clicked(e);
    }
}
void ui_event_Label1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        SetMoveValue(e);
    }
}
void ui_event_Btn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move2Clicked(e);
    }
}
void ui_event_Btn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move1Clicked(e);
    }
}
void ui_event_BtnDel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DeleteMove(e);
    }
}
void ui_event_Btn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move4Clicked(e);
    }
}
void ui_event_Btn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move5Clicked(e);
    }
}
void ui_event_Btn6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move6Clicked(e);
    }
}
void ui_event_Btn05(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move05Clicked(e);
    }
}
void ui_event_Btn7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move7Clicked(e);
    }
}
void ui_event_Btn8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move8Clicked(e);
    }
}
void ui_event_Btn9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move9Clicked(e);
    }
}
void ui_event_Btn025(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move025Clicked(e);
    }
}
void ui_event_BtnComma(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        MoveCommaClicked(e);
    }
}
void ui_event_Btn0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move0Clicked(e);
    }
}
void ui_event_Btn033(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move033Clicked(e);
    }
}
void ui_event_Btn0125(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move0125Clicked(e);
    }
}
void ui_event_BtnGo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        MoveToPosition(e);
    }
}
void ui_event_BtnSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrSettings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScrSettings_screen_init);
    }
}
void ui_event_BtnSteps(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrSetStep, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScrSetStep_screen_init);
    }
}
void ui_event_BtnClose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrMove, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScrMove_screen_init);
    }
}
void ui_event_Btn10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move1Clicked(e);
    }
}
void ui_event_Label3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        SetMoveValue(e);
    }
}
void ui_event_Btn11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move2Clicked(e);
    }
}
void ui_event_Btn12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move1Clicked(e);
    }
}
void ui_event_BtnDel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DeleteMove(e);
    }
}
void ui_event_Btn13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move4Clicked(e);
    }
}
void ui_event_Btn14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move5Clicked(e);
    }
}
void ui_event_Btn15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move6Clicked(e);
    }
}
void ui_event_Btn16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move05Clicked(e);
    }
}
void ui_event_Btn17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move7Clicked(e);
    }
}
void ui_event_Btn18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move8Clicked(e);
    }
}
void ui_event_Btn19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move9Clicked(e);
    }
}
void ui_event_Btn20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move025Clicked(e);
    }
}
void ui_event_BtnComma1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        MoveCommaClicked(e);
    }
}
void ui_event_Btn21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move0Clicked(e);
    }
}
void ui_event_Btn22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move033Clicked(e);
    }
}
void ui_event_Btn23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Move0125Clicked(e);
    }
}
void ui_event_BtnGo1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        MoveToPosition(e);
    }
}
void ui_event_BtnClose2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrMove, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScrMove_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScrMove_screen_init();
    ui_ScrSettings_screen_init();
    ui_ScrSetStep_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScrMove);
}
