// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Esp32TableSaw_SL

#ifndef _ESP32TABLESAW_SL_UI_H
#define _ESP32TABLESAW_SL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScrMove
void ui_ScrMove_screen_init(void);
extern lv_obj_t * ui_ScrMove;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_lblPosition;
extern lv_obj_t * ui_Panel5;
void ui_event_Btn1(lv_event_t * e);
extern lv_obj_t * ui_Btn1;
void ui_event_Label1(lv_event_t * e);
extern lv_obj_t * ui_Label1;
void ui_event_Btn2(lv_event_t * e);
extern lv_obj_t * ui_Btn2;
extern lv_obj_t * ui_Label2;
void ui_event_Btn3(lv_event_t * e);
extern lv_obj_t * ui_Btn3;
extern lv_obj_t * ui_Label4;
void ui_event_BtnDel(lv_event_t * e);
extern lv_obj_t * ui_BtnDel;
extern lv_obj_t * ui_Label5;
void ui_event_Btn4(lv_event_t * e);
extern lv_obj_t * ui_Btn4;
extern lv_obj_t * ui_Label6;
void ui_event_Btn5(lv_event_t * e);
extern lv_obj_t * ui_Btn5;
extern lv_obj_t * ui_Label7;
void ui_event_Btn6(lv_event_t * e);
extern lv_obj_t * ui_Btn6;
extern lv_obj_t * ui_Label8;
void ui_event_Btn05(lv_event_t * e);
extern lv_obj_t * ui_Btn05;
extern lv_obj_t * ui_Label9;
void ui_event_Btn7(lv_event_t * e);
extern lv_obj_t * ui_Btn7;
extern lv_obj_t * ui_Label10;
void ui_event_Btn8(lv_event_t * e);
extern lv_obj_t * ui_Btn8;
extern lv_obj_t * ui_Label11;
void ui_event_Btn9(lv_event_t * e);
extern lv_obj_t * ui_Btn9;
extern lv_obj_t * ui_Label12;
void ui_event_Btn025(lv_event_t * e);
extern lv_obj_t * ui_Btn025;
extern lv_obj_t * ui_Label13;
void ui_event_BtnComma(lv_event_t * e);
extern lv_obj_t * ui_BtnComma;
extern lv_obj_t * ui_Label14;
void ui_event_Btn0(lv_event_t * e);
extern lv_obj_t * ui_Btn0;
extern lv_obj_t * ui_Label15;
void ui_event_Btn033(lv_event_t * e);
extern lv_obj_t * ui_Btn033;
extern lv_obj_t * ui_Label16;
void ui_event_Btn0125(lv_event_t * e);
extern lv_obj_t * ui_Btn0125;
extern lv_obj_t * ui_Label17;
void ui_event_BtnGo(lv_event_t * e);
extern lv_obj_t * ui_BtnGo;
extern lv_obj_t * ui_Label18;
void ui_event_BtnSettings(lv_event_t * e);
extern lv_obj_t * ui_BtnSettings;
extern lv_obj_t * ui_Image2;
// SCREEN: ui_ScrSettings
void ui_ScrSettings_screen_init(void);
extern lv_obj_t * ui_ScrSettings;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_BtnPos1;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_BtnPos2;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_BtnPos3;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_BtnProbe;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Image6;
void ui_event_BtnSteps(lv_event_t * e);
extern lv_obj_t * ui_BtnSteps;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Image7;
void ui_event_BtnClose(lv_event_t * e);
extern lv_obj_t * ui_BtnClose;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Image1;
// SCREEN: ui_ScrSetStep
void ui_ScrSetStep_screen_init(void);
extern lv_obj_t * ui_ScrSetStep;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_lblPosition1;
extern lv_obj_t * ui_Panel4;
void ui_event_Btn10(lv_event_t * e);
extern lv_obj_t * ui_Btn10;
void ui_event_Label3(lv_event_t * e);
extern lv_obj_t * ui_Label3;
void ui_event_Btn11(lv_event_t * e);
extern lv_obj_t * ui_Btn11;
extern lv_obj_t * ui_Label25;
void ui_event_Btn12(lv_event_t * e);
extern lv_obj_t * ui_Btn12;
extern lv_obj_t * ui_Label26;
void ui_event_BtnDel1(lv_event_t * e);
extern lv_obj_t * ui_BtnDel1;
extern lv_obj_t * ui_Label27;
void ui_event_Btn13(lv_event_t * e);
extern lv_obj_t * ui_Btn13;
extern lv_obj_t * ui_Label28;
void ui_event_Btn14(lv_event_t * e);
extern lv_obj_t * ui_Btn14;
extern lv_obj_t * ui_Label29;
void ui_event_Btn15(lv_event_t * e);
extern lv_obj_t * ui_Btn15;
extern lv_obj_t * ui_Label30;
void ui_event_Btn16(lv_event_t * e);
extern lv_obj_t * ui_Btn16;
extern lv_obj_t * ui_Label31;
void ui_event_Btn17(lv_event_t * e);
extern lv_obj_t * ui_Btn17;
extern lv_obj_t * ui_Label32;
void ui_event_Btn18(lv_event_t * e);
extern lv_obj_t * ui_Btn18;
extern lv_obj_t * ui_Label33;
void ui_event_Btn19(lv_event_t * e);
extern lv_obj_t * ui_Btn19;
extern lv_obj_t * ui_Label34;
void ui_event_Btn20(lv_event_t * e);
extern lv_obj_t * ui_Btn20;
extern lv_obj_t * ui_Label35;
void ui_event_BtnComma1(lv_event_t * e);
extern lv_obj_t * ui_BtnComma1;
extern lv_obj_t * ui_Label36;
void ui_event_Btn21(lv_event_t * e);
extern lv_obj_t * ui_Btn21;
extern lv_obj_t * ui_Label37;
void ui_event_Btn22(lv_event_t * e);
extern lv_obj_t * ui_Btn22;
extern lv_obj_t * ui_Label38;
void ui_event_Btn23(lv_event_t * e);
extern lv_obj_t * ui_Btn23;
extern lv_obj_t * ui_Label39;
void ui_event_BtnGo1(lv_event_t * e);
extern lv_obj_t * ui_BtnGo1;
extern lv_obj_t * ui_Label40;
void ui_event_BtnClose2(lv_event_t * e);
extern lv_obj_t * ui_BtnClose2;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_478973782);    // assets\settings_24-white.png
LV_IMG_DECLARE(ui_img_position1_24_white_png);    // assets\position1_24_white.png
LV_IMG_DECLARE(ui_img_position2_24_white_png);    // assets\position2_24_white.png
LV_IMG_DECLARE(ui_img_position3_24_white_png);    // assets\position3_24_white.png
LV_IMG_DECLARE(ui_img_2104542103);    // assets\Probe-24-white.png
LV_IMG_DECLARE(ui_img_561644076);    // assets\steps-24-white.png
LV_IMG_DECLARE(ui_img_1297254713);    // assets\close_24-white.png
LV_IMG_DECLARE(ui_img_settings_fill0_wght400_grad0_opsz48_png);    // assets\settings_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(ui_img_settings_fill0_wght400_grad0_opsz24_png);    // assets\settings_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(ui_img_settings_24_png);    // assets\settings_24.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
