// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Esp32TableSaw_SL

#ifndef _ESP32TABLESAW_SL_UI_H
#define _ESP32TABLESAW_SL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScrMove
void ui_ScrMove_screen_init(void);
extern lv_obj_t *ui_ScrMove;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_lblPosition;
extern lv_obj_t *ui_Panel5;
void ui_event_ButtonKey1( lv_event_t * e);
extern lv_obj_t *ui_ButtonKey1;
extern lv_obj_t *ui_LabelKey1;
void ui_event_ButtonKey2( lv_event_t * e);
extern lv_obj_t *ui_ButtonKey2;
extern lv_obj_t *ui_LabelKey2;
void ui_event_ButtonKey3( lv_event_t * e);
extern lv_obj_t *ui_ButtonKey3;
extern lv_obj_t *ui_LabelKey3;
void ui_event_ButtonKeyDel( lv_event_t * e);
extern lv_obj_t *ui_ButtonKeyDel;
extern lv_obj_t *ui_LabelKeyDel;
void ui_event_ButtonKey4( lv_event_t * e);
extern lv_obj_t *ui_ButtonKey4;
extern lv_obj_t *ui_LabelKey4;
void ui_event_ButtonKey5( lv_event_t * e);
extern lv_obj_t *ui_ButtonKey5;
extern lv_obj_t *ui_LabelKey5;
void ui_event_ButtonKey6( lv_event_t * e);
extern lv_obj_t *ui_ButtonKey6;
extern lv_obj_t *ui_LabelKey6;
void ui_event_ButtonKeyPos1( lv_event_t * e);
extern lv_obj_t *ui_ButtonKeyPos1;
extern lv_obj_t *ui_LabelKeyPos1;
void ui_event_ButtonKey7( lv_event_t * e);
extern lv_obj_t *ui_ButtonKey7;
extern lv_obj_t *ui_LabelKey7;
void ui_event_ButtonKey8( lv_event_t * e);
extern lv_obj_t *ui_ButtonKey8;
extern lv_obj_t *ui_LabelKey8;
void ui_event_ButtonKey9( lv_event_t * e);
extern lv_obj_t *ui_ButtonKey9;
extern lv_obj_t *ui_LabelKey9;
void ui_event_ButtonKeyPos2( lv_event_t * e);
extern lv_obj_t *ui_ButtonKeyPos2;
extern lv_obj_t *ui_LabelKeyPos2;
void ui_event_ButtonKeyComma( lv_event_t * e);
extern lv_obj_t *ui_ButtonKeyComma;
extern lv_obj_t *ui_LabelKeyComma;
void ui_event_ButtonKey0( lv_event_t * e);
extern lv_obj_t *ui_ButtonKey0;
extern lv_obj_t *ui_LabelKey0;
void ui_event_ButtonKey05( lv_event_t * e);
extern lv_obj_t *ui_ButtonKey05;
extern lv_obj_t *ui_LabelKey05;
void ui_event_ButtonKeyPos3( lv_event_t * e);
extern lv_obj_t *ui_ButtonKeyPos3;
extern lv_obj_t *ui_LabelKeyPos3;
void ui_event_ButtonKeyValidate( lv_event_t * e);
extern lv_obj_t *ui_ButtonKeyValidate;
extern lv_obj_t *ui_LabelKeyValidate;
void ui_event_ButtonKeySettings( lv_event_t * e);
extern lv_obj_t *ui_ButtonKeySettings;
extern lv_obj_t *ui_LabelKeySettings;
// SCREEN: ui_ScrSettings
void ui_ScrSettings_screen_init(void);
extern lv_obj_t *ui_ScrSettings;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_ButtonSettingsPos1Enter;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_BtnPos2;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_BtnPos3;
extern lv_obj_t *ui_Label21;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_BtnProbe;
extern lv_obj_t *ui_Label22;
extern lv_obj_t *ui_Image6;
void ui_event_BtnSteps( lv_event_t * e);
extern lv_obj_t *ui_BtnSteps;
extern lv_obj_t *ui_Label23;
extern lv_obj_t *ui_Image7;
void ui_event_BtnClose( lv_event_t * e);
extern lv_obj_t *ui_BtnClose;
extern lv_obj_t *ui_Label24;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_478973782);   // assets\settings_24-white.png
LV_IMG_DECLARE( ui_img_position1_24_white_png);   // assets\position1_24_white.png
LV_IMG_DECLARE( ui_img_position2_24_white_png);   // assets\position2_24_white.png
LV_IMG_DECLARE( ui_img_position3_24_white_png);   // assets\position3_24_white.png
LV_IMG_DECLARE( ui_img_2104542103);   // assets\Probe-24-white.png
LV_IMG_DECLARE( ui_img_561644076);   // assets\steps-24-white.png
LV_IMG_DECLARE( ui_img_1297254713);   // assets\close_24-white.png
LV_IMG_DECLARE( ui_img_settings_24_png);   // assets\settings_24.png
LV_IMG_DECLARE( ui_img_settings_fill0_wght400_grad0_opsz24_png);   // assets\settings_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE( ui_img_settings_fill0_wght400_grad0_opsz48_png);   // assets\settings_FILL0_wght400_GRAD0_opsz48.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
