// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Esp32TableSaw_SL

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ButtonKey1Clicked(lv_event_t * e);
void ButtonKey2Clicked(lv_event_t * e);
void ButtonKey3Clicked(lv_event_t * e);
void ButtonKeyDelClicked(lv_event_t * e);
void ButtonKey4Clicked(lv_event_t * e);
void ButtonKey5Clicked(lv_event_t * e);
void ButtonKey6Clicked(lv_event_t * e);
void ButtonKeyPos1Clicked(lv_event_t * e);
void ButtonKey7Clicked(lv_event_t * e);
void ButtonKey8Clicked(lv_event_t * e);
void ButtonKey9Clicked(lv_event_t * e);
void ButtonKeyPos2Clicked(lv_event_t * e);
void ButtonKeyCommaClicked(lv_event_t * e);
void ButtonKey05Clicked(lv_event_t * e);
void ButtonKeyPos3Clicked(lv_event_t * e);
void ButtonKeyValidateClicked(lv_event_t * e);
void ButtonKeySettingsClicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
