// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Esp32TableSaw_SL

#include "ui.h"
#include <lvgl.h>
#include <stdio.h>
#include <stdlib.h>
#include <cstring>
#include "StepperMotor.h"
#include "ScreenPosition.h"

extern ScreenPosition screenPosition;

// class UIEvents {
// public:
extern "C" {
    

    void ButtonKey1Clicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKey2Clicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKey3Clicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKeyDelClicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKey4Clicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKey5Clicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKey6Clicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKeyPos1Clicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKey7Clicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKey8Clicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKey9Clicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKeyPos2Clicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKeyCommaClicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKey05Clicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKeyPos3Clicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKeyValidateClicked(lv_event_t * e)
    {
        // Your code here
    }

    void ButtonKeySettingsClicked(lv_event_t * e)
    {
        // Your code here
    }
}
