// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Esp32TableSaw_SL

#include "ui.h"
#include <lvgl.h>
#include <stdio.h>
#include <stdlib.h>
#include <cstring>
#include "StepperMotor.h"
#include "ScreenPosition.h"

extern ScreenPosition screenPosition;

// class UIEvents {
// public:
extern "C" {
    
    void Move1Clicked(lv_event_t * e) {
        screenPosition.enterDigitOrDecimal("1");
    }

    void Move2Clicked(lv_event_t * e) {
        screenPosition.enterDigitOrDecimal("2");
    }

    void Move3Clicked(lv_event_t * e) {
        screenPosition.enterDigitOrDecimal("3");
    }

    void SetMoveValue(lv_event_t * e) {
        // Your code here
    }

    void DeleteMove(lv_event_t * e) {
        screenPosition.clear();
    }

    void Move4Clicked(lv_event_t * e) {
        screenPosition.enterDigitOrDecimal("4");
    }

    void Move5Clicked(lv_event_t * e) {
        screenPosition.enterDigitOrDecimal("5");
    }

    void Move6Clicked(lv_event_t * e) {
        screenPosition.enterDigitOrDecimal("6");
    }

    void Move05Clicked(lv_event_t * e) {
        screenPosition.enterDigitOrDecimal("0.5");
    }

    void Move7Clicked(lv_event_t * e) {
        screenPosition.enterDigitOrDecimal("7");
    }

    void Move8Clicked(lv_event_t * e) {
        screenPosition.enterDigitOrDecimal("8");
    }

    void Move9Clicked(lv_event_t * e) {
        screenPosition.enterDigitOrDecimal("9");
    }

    void Move025Clicked(lv_event_t * e) {
        screenPosition.enterDigitOrDecimal("0.25");
    }

    void MoveCommaClicked(lv_event_t * e) {
        screenPosition.enterDigitOrDecimal(",");
    }

    void Move0Clicked(lv_event_t * e) {
        screenPosition.enterDigitOrDecimal("0");
    }

    void Move033Clicked(lv_event_t * e) {
        screenPosition.enterDigitOrDecimal("0.33");
    }

    void Move0125Clicked(lv_event_t * e) {
        screenPosition.enterDigitOrDecimal("0.125");
    }

    void MoveToPosition(lv_event_t * e) {
        screenPosition.validate();
    }

    void Move12Clicked(lv_event_t * e) {
        // Your code here
    }
}
// };
