// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Esp32TableSaw_SL

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

bool containsComma(const char * str);
float convertString(const char * str);

void Move1Clicked(lv_event_t * e);
void Move2Clicked(lv_event_t * e);
void Move3Clicked(lv_event_t * e);
void Move4Clicked(lv_event_t * e);
void Move5Clicked(lv_event_t * e);
void Move6Clicked(lv_event_t * e);
void Move05Clicked(lv_event_t * e);
void Move7Clicked(lv_event_t * e);
void Move8Clicked(lv_event_t * e);
void Move9Clicked(lv_event_t * e);
void Move025Clicked(lv_event_t * e);
void MoveCommaClicked(lv_event_t * e);
void Move0Clicked(lv_event_t * e);
void Move033Clicked(lv_event_t * e);
void Move0125Clicked(lv_event_t * e);
void MoveToPosition(lv_event_t * e);
void Move12Clicked(lv_event_t * e);

void SetMoveValue(lv_event_t * e);
void DeleteMove(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
