// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Esp32TableSaw_SL

#include "ui.h"
#include <lvgl.h>

void Move1Clicked(lv_event_t * e)
{
	// Your code here
	LV_LOG_USER("Clicked");
	
	lv_label_set_text_fmt(ui_lblPosition, "1");
	//lv_label_set_text(ui_lblPosition, "1");
}

void SetMoveValue(lv_event_t * e)
{
	// Your code here
}

void Move2Clicked(lv_event_t * e)
{
	// Your code here
}

void DeleteMove(lv_event_t * e)
{
	// Your code here
}

void Move4Clicked(lv_event_t * e)
{
	// Your code here
}

void Move5Clicked(lv_event_t * e)
{
	// Your code here
}

void Move6Clicked(lv_event_t * e)
{
	// Your code here
}

void Move05Clicked(lv_event_t * e)
{
	// Your code here
}

void Move7Clicked(lv_event_t * e)
{
	// Your code here
}

void Move8Clicked(lv_event_t * e)
{
	// Your code here
}

void Move9Clicked(lv_event_t * e)
{
	// Your code here
}

void Move025Clicked(lv_event_t * e)
{
	// Your code here
}

void MoveCommaClicked(lv_event_t * e)
{
	// Your code here
}

void Move0Clicked(lv_event_t * e)
{
	// Your code here
}

void Move033Clicked(lv_event_t * e)
{
	// Your code here
}

void Move0125Clicked(lv_event_t * e)
{
	// Your code here
}

void MoveToPosition(lv_event_t * e)
{
	// Your code here
}
